#!/bin/sh
hist_path="/tmp/cpu_usage_hist"
new_stat=$(sed q /proc/stat)
[ -f "$hist_path" ] && old_stat=$(cat "$hist_path") || old_stat=$new_stat
echo "$new_stat" > "$hist_path"

result=$(printf "${old_stat}\n${new_stat}" \
    | awk '{print $5+$6, $2+$3+$4+$5+$6+$7+$8+$9+$10+$11}' \
    | xargs \
    | awk '{printf "%2.0f%", 100*(1-($3-$1)/($4-$2))}')
echo "$result"
